services:
  server:
    build:
      context: ..
      dockerfile: api/Dockerfile.server
    image: secure-nas-server
    container_name: secure-nas-server
    hostname: secure-nas-server
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN  # Required for mount/umount operations
    ports:
      - "8443:8443"    # mTLS port
      - "2049:2049"    # NFS port
      - "5354:5353/udp"  # mDNS port (mapped to 5354 to avoid conflict with macOS)
    volumes:
      # Use a named volume for NFS exports (NFS requires a real filesystem, not overlay)
      - nfs-storage:/app/demo_storage
    networks:
      - nas-network
    restart: unless-stopped

  client:
    build:
      context: ..
      dockerfile: api/Dockerfile.client
    image: secure-nas-client
    container_name: secure-nas-client
    cap_add:
      - SYS_ADMIN  # Required for NFS mount operations
    depends_on:
      - server
    networks:
      - nas-network
    stdin_open: true
    tty: true
    # Use startup script with NO hostname - forces mDNS discovery
    command: /app/start.sh
    profiles:
      - client  # Only start when explicitly requested

networks:
  nas-network:
    driver: bridge

volumes:
  # Named volume for NFS storage - provides a real filesystem that NFS can export
  nfs-storage:
    driver: local
