#!/usr/bin/env bash
#
# ThumbsUp Host Setup Script
# Generates .env, configures the hostname, and sets up Avahi mDNS
# on a Debian/Raspberry Pi OS host.
#
# Usage:
#   sudo ./setup.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Must run as root
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    echo "Error: this script must be run as root (use sudo ./setup.sh)"
    exit 1
fi

# ---------------------------------------------------------------------------
# Generate .env if it doesn't exist
# ---------------------------------------------------------------------------
ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    echo "Found existing .env — loading configuration"
    set -o allexport
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +o allexport
else
    echo
    echo "No .env found — let's generate one."
    echo

    # Prompt for ADMIN_PIN
    while true; do
        read -rp "Admin PIN (min 4 digits, used for first login): " ADMIN_PIN
        if [[ ${#ADMIN_PIN} -ge 4 ]]; then
            break
        fi
        echo "PIN must be at least 4 characters."
    done

    # Prompt for MDNS_HOSTNAME
    read -rp "mDNS hostname [thumbsup]: " MDNS_HOSTNAME
    MDNS_HOSTNAME="${MDNS_HOSTNAME:-thumbsup}"

    cat > "$ENV_FILE" <<EOF
# ThumbsUp Configuration — generated by setup.sh
# Edit this file to change settings, then run: docker compose up -d

ADMIN_PIN=${ADMIN_PIN}
MDNS_HOSTNAME=${MDNS_HOSTNAME}
EOF

    echo
    echo ".env generated at $ENV_FILE"
fi

MDNS_HOSTNAME="${MDNS_HOSTNAME:-thumbsup}"
ADMIN_PIN="${ADMIN_PIN:-}"

if [[ -z "$ADMIN_PIN" || ${#ADMIN_PIN} -lt 4 ]]; then
    echo "Error: ADMIN_PIN must be set in $ENV_FILE and be at least 4 characters to avoid using an insecure default."
    exit 1
fi
echo
echo "========================================"
echo " ThumbsUp Host Setup"
echo " Hostname: ${MDNS_HOSTNAME}.local"
echo "========================================"
echo

# ---------------------------------------------------------------------------
# 1. Set system hostname
# ---------------------------------------------------------------------------
CURRENT_HOSTNAME="$(hostname)"

if [[ "$CURRENT_HOSTNAME" != "$MDNS_HOSTNAME" ]]; then
    echo "Setting hostname: $CURRENT_HOSTNAME -> $MDNS_HOSTNAME"
    hostnamectl set-hostname "$MDNS_HOSTNAME"

    # Update /etc/hosts so sudo and local resolution work without warnings
    if grep -q "$CURRENT_HOSTNAME" /etc/hosts; then
        sed -i "s/$CURRENT_HOSTNAME/$MDNS_HOSTNAME/g" /etc/hosts
        echo "Updated /etc/hosts"
    else
        # Ensure 127.0.1.1 entry exists for the new hostname
        if grep -q "127.0.1.1" /etc/hosts; then
            sed -i "s/127.0.1.1.*/127.0.1.1\t$MDNS_HOSTNAME/" /etc/hosts
        else
            echo -e "127.0.1.1\t$MDNS_HOSTNAME" >> /etc/hosts
        fi
        echo "Added $MDNS_HOSTNAME to /etc/hosts"
    fi
else
    echo "Hostname already set to $MDNS_HOSTNAME — skipping"
fi

# ---------------------------------------------------------------------------
# 2. Install avahi-daemon
# ---------------------------------------------------------------------------
if ! command -v avahi-daemon &>/dev/null; then
    echo "Installing avahi-daemon..."
    apt-get update -qq
    apt-get install -y --no-install-recommends avahi-daemon avahi-utils
else
    echo "avahi-daemon already installed"
fi

# ---------------------------------------------------------------------------
# 3. Install the mDNS service advertisement file
# ---------------------------------------------------------------------------
AVAHI_SERVICE_SRC="$SCRIPT_DIR/backend/config/thumbsup.avahi-service"
AVAHI_SERVICE_DST="/etc/avahi/services/thumbsup.service"

if [[ -f "$AVAHI_SERVICE_SRC" ]]; then
    cp "$AVAHI_SERVICE_SRC" "$AVAHI_SERVICE_DST"
    echo "Installed Avahi service file -> $AVAHI_SERVICE_DST"
else
    echo "Warning: $AVAHI_SERVICE_SRC not found — skipping service file install"
fi

# ---------------------------------------------------------------------------
# 4. Enable and restart avahi-daemon
# ---------------------------------------------------------------------------
systemctl enable avahi-daemon
systemctl restart avahi-daemon
echo "avahi-daemon enabled and restarted"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo
echo "✅ Host setup complete!"
echo "   Device will be discoverable at: https://${MDNS_HOSTNAME}.local"
echo
echo "Next steps:"
echo "  docker compose up -d"
echo
