#!/usr/bin/env bash
#
# TerraCrate Host Setup Script
# Generates .env, sets up Avahi mDNS, and configures the WiFi AP fallback
# on a Debian/Raspberry Pi OS host.
#
# Usage:
#   sudo ./setup.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Must run as root
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    echo "Error: this script must be run as root (use sudo ./setup.sh)"
    exit 1
fi

# ---------------------------------------------------------------------------
# Generate .env if it doesn't exist
# ---------------------------------------------------------------------------
ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    echo "Found existing .env — loading configuration"
    set -o allexport
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +o allexport
else
    echo
    echo "No .env found — generating default configuration."
    echo

    install -m 600 /dev/null "$ENV_FILE"
    cat > "$ENV_FILE" <<EOF
# TerraCrate Configuration — generated by setup.sh
# Edit this file to change settings, then run: docker compose up -d

MDNS_HOSTNAME=terracrate
EOF

    echo ".env generated at $ENV_FILE"
    echo "To customize the mDNS hostname, edit MDNS_HOSTNAME in $ENV_FILE"
    echo
fi

# Ensure .env is not world-readable (it stores the AP passphrase)
chmod 600 "$ENV_FILE"
chown "${SUDO_USER:-root}:${SUDO_USER:-root}" "$ENV_FILE"

MDNS_HOSTNAME="${MDNS_HOSTNAME:-terracrate}"

# Validate MDNS_HOSTNAME: allow only lowercase letters, digits, and hyphens
if [[ ! "$MDNS_HOSTNAME" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]; then
    echo "Error: MDNS_HOSTNAME ('$MDNS_HOSTNAME') is invalid."
    echo "       Must be 1–63 chars, lowercase letters, digits, and hyphens only."
    exit 1
fi

# ---------------------------------------------------------------------------
# Require AP_PASSPHRASE — prompt if not already set in .env
# ---------------------------------------------------------------------------
if [[ -z "${AP_PASSPHRASE:-}" ]]; then
    echo
    echo "WiFi AP passphrase is required (8–63 characters)."
    while true; do
        read -r -s -p "Enter AP passphrase: " AP_PASSPHRASE
        echo
        if [[ ${#AP_PASSPHRASE} -ge 8 && ${#AP_PASSPHRASE} -le 63 ]]; then
            break
        fi
        echo "Passphrase must be 8–63 characters. Please try again."
    done
    # Persist to .env so re-runs are non-interactive.
    # Single-quote the value to prevent shell metacharacter interpretation.
    printf '\n# WiFi Access Point passphrase\nAP_PASSPHRASE=\x27%s\x27\n' "${AP_PASSPHRASE//\x27/\x27\"\x27\"\x27}" >> "$ENV_FILE"
    echo "AP_PASSPHRASE saved to $ENV_FILE"
fi

echo
echo "========================================"
echo " TerraCrate Host Setup"
echo "========================================"
echo

# ---------------------------------------------------------------------------
# 1. Determine all packages needed and install in one pass
# ---------------------------------------------------------------------------
NEEDED_PKGS=()
command -v avahi-daemon &>/dev/null || NEEDED_PKGS+=(avahi-daemon avahi-utils)
command -v hostapd      &>/dev/null || NEEDED_PKGS+=(hostapd)
command -v dnsmasq      &>/dev/null || NEEDED_PKGS+=(dnsmasq)

if [[ ${#NEEDED_PKGS[@]} -gt 0 ]]; then
    echo "Installing: ${NEEDED_PKGS[*]}..."
    apt-get update -qq
    apt-get install -y --no-install-recommends "${NEEDED_PKGS[@]}"
else
    echo "All required packages already installed"
fi

# ---------------------------------------------------------------------------
# 2. Install the mDNS service advertisement file
# ---------------------------------------------------------------------------
AVAHI_SERVICE_SRC="$SCRIPT_DIR/config/terracrate.avahi-service"
AVAHI_SERVICE_DST="/etc/avahi/services/terracrate.service"

if [[ -f "$AVAHI_SERVICE_SRC" ]]; then
    cp "$AVAHI_SERVICE_SRC" "$AVAHI_SERVICE_DST"
    echo "Installed Avahi service file -> $AVAHI_SERVICE_DST"
else
    echo "Warning: $AVAHI_SERVICE_SRC not found — skipping service file install"
fi

# ---------------------------------------------------------------------------
# 3. Enable and restart avahi-daemon
# ---------------------------------------------------------------------------
# Set the system hostname to match MDNS_HOSTNAME so <hostname>.local resolves
if [[ "$(hostnamectl hostname 2>/dev/null || hostname)" != "$MDNS_HOSTNAME" ]]; then
    hostnamectl set-hostname "$MDNS_HOSTNAME"
    echo "System hostname set to $MDNS_HOSTNAME"
fi

systemctl enable avahi-daemon
systemctl restart avahi-daemon
echo "avahi-daemon enabled and restarted"

# ---------------------------------------------------------------------------
# 4. Install WiFi Access Point fallback
# ---------------------------------------------------------------------------
echo
echo "--- WiFi Access Point Fallback Setup ---"

# (Packages already installed in step 1 above)

# Install the fallback check script
WIFI_CHECK_SRC="$SCRIPT_DIR/config/wifi-check.sh"
WIFI_CHECK_DST="/usr/local/bin/wifi-check.sh"
if [[ -f "$WIFI_CHECK_SRC" ]]; then
    cp "$WIFI_CHECK_SRC" "$WIFI_CHECK_DST"
    chmod +x "$WIFI_CHECK_DST"
    echo "Installed wifi-check.sh -> $WIFI_CHECK_DST"
else
    echo "Warning: $WIFI_CHECK_SRC not found — skipping wifi-check.sh install"
fi

# Install hostapd configuration (skip if already customized by the user)
HOSTAPD_CONF_SRC="$SCRIPT_DIR/config/hostapd.conf"
HOSTAPD_CONF_DST="/etc/hostapd/hostapd.conf"
if [[ -f "$HOSTAPD_CONF_DST" ]]; then
    echo "Existing $HOSTAPD_CONF_DST kept — edit it to change SSID/password"
elif [[ -f "$HOSTAPD_CONF_SRC" ]]; then
    # Substitute the placeholder using awk so special characters in the
    # passphrase (/, &, \, etc.) are handled safely.
    awk -v pass="$AP_PASSPHRASE" \
        '/^wpa_passphrase=AP_PASSPHRASE$/{print "wpa_passphrase=" pass; next} {print}' \
        "$HOSTAPD_CONF_SRC" > "$HOSTAPD_CONF_DST"
    chmod 600 "$HOSTAPD_CONF_DST"
    echo "Installed hostapd.conf -> $HOSTAPD_CONF_DST"
    echo "  AP SSID: TerraCrate-AP  (change ssid= in $HOSTAPD_CONF_DST if desired)"
else
    echo "Warning: $HOSTAPD_CONF_SRC not found — skipping hostapd.conf install"
fi

# Install dnsmasq configuration (skip if already customized by the user)
DNSMASQ_CONF_SRC="$SCRIPT_DIR/config/dnsmasq.conf"
DNSMASQ_CONF_DST="/etc/dnsmasq.conf"
if [[ -f "$DNSMASQ_CONF_DST" ]]; then
    echo "Existing $DNSMASQ_CONF_DST kept — edit it to adjust DHCP range"
elif [[ -f "$DNSMASQ_CONF_SRC" ]]; then
    cp "$DNSMASQ_CONF_SRC" "$DNSMASQ_CONF_DST"
    echo "Installed dnsmasq.conf -> $DNSMASQ_CONF_DST"
else
    echo "Warning: $DNSMASQ_CONF_SRC not found — skipping dnsmasq.conf install"
fi

# Unmask hostapd and dnsmasq — on Raspberry Pi OS they ship masked by default,
# which causes "Unit is masked" errors when wifi-check.sh tries to start them.
systemctl unmask hostapd dnsmasq 2>/dev/null || true

# Disable hostapd and dnsmasq from auto-starting — wifi-check.sh starts them
# only when the Pi fails to join a known network.
systemctl disable hostapd dnsmasq 2>/dev/null || true
echo "hostapd and dnsmasq unmasked and disabled from auto-start (wifi-check.sh controls them)"

# ---------------------------------------------------------------------------
# 5. LUKS Drive Encryption (optional)
# ---------------------------------------------------------------------------
echo
echo "--- LUKS Drive Encryption Setup ---"
LUKS_ENABLED=false

# Check for an existing LUKS setup (re-run detection)
if [[ -f /etc/terracrate/luks.key ]] && [[ -f /etc/systemd/system/terracrate-luks.service ]]; then
    # Extract the UUID from the installed service file
    LUKS_UUID=$(grep -oP 'by-uuid/\K[^ ]+' /etc/systemd/system/terracrate-luks.service || true)
    if [[ -n "$LUKS_UUID" ]]; then
        echo "Existing LUKS configuration detected (UUID=$LUKS_UUID)"
        echo
        echo "  [1] Update service files only (keep existing encryption)"
        echo "  [2] Re-encrypt drive (DESTROYS ALL DATA)"
        echo "  [3] Skip LUKS setup"
        echo
        read -r -p "Choose [1/2/3] (default: 1): " LUKS_RERUN_CHOICE
        LUKS_RERUN_CHOICE="${LUKS_RERUN_CHOICE:-1}"

        if [[ "$LUKS_RERUN_CHOICE" == "1" ]]; then
            echo "Reinstalling service files from updated templates..."

            # Close any stale mapper with the old name if it differs
            for mapper in $(dmsetup ls --target crypt 2>/dev/null | awk '{print $1}'); do
                if [[ "$mapper" != "terracrate-store" ]]; then
                    # Check if this mapper is backed by our LUKS UUID
                    backing=$(cryptsetup status "$mapper" 2>/dev/null | awk '/device:/{print $2}')
                    if [[ -n "$backing" ]] && [[ "$(blkid -s UUID -o value "$backing" 2>/dev/null)" == "$LUKS_UUID" ]]; then
                        echo "Renaming old mapper '$mapper' -> closing and reopening as terracrate-store..."
                        umount /mnt/storage 2>/dev/null || true
                        cryptsetup luksClose "$mapper" 2>/dev/null || true
                    fi
                fi
            done

            # Reinstall terracrate-luks.service
            LUKS_SVC_SRC="$SCRIPT_DIR/config/terracrate-luks.service"
            LUKS_SVC_DST="/etc/systemd/system/terracrate-luks.service"
            if [[ -f "$LUKS_SVC_SRC" ]]; then
                sed "s|__LUKS_UUID__|$LUKS_UUID|g" "$LUKS_SVC_SRC" > "$LUKS_SVC_DST"
                echo "Reinstalled terracrate-luks.service"
            fi

            systemctl daemon-reload
            systemctl reset-failed terracrate-luks 2>/dev/null || true
            systemctl enable terracrate-luks
            systemctl start terracrate-luks
            echo "LUKS services updated and started"

            # Ensure docker-compose.yml uses /mnt/storage
            sed -i "s|^\(\s*-\s*\)./backend/api/storage:/app/storage|\1/mnt/storage:/app/storage|" \
                "$SCRIPT_DIR/docker-compose.yml"

            LUKS_ENABLED=true

        elif [[ "$LUKS_RERUN_CHOICE" == "2" ]]; then
            echo "Re-encryption selected — will proceed to fresh LUKS setup below."
            # Stop services and close existing LUKS so fresh setup can claim the drive
            systemctl stop terracrate 2>/dev/null || true
            systemctl stop terracrate-luks 2>/dev/null || true
            umount /mnt/storage 2>/dev/null || true
            for mapper in $(dmsetup ls --target crypt 2>/dev/null | awk '{print $1}'); do
                cryptsetup luksClose "$mapper" 2>/dev/null || true
            done
            rm -f /etc/terracrate/luks.key
            # LUKS_ENABLED stays false → falls through to fresh setup
        else
            echo "Skipping LUKS setup."
            LUKS_ENABLED=true  # prevent fresh setup from running
        fi
    fi
fi

if [[ "$LUKS_ENABLED" == "false" ]]; then
# Detect the boot drive so we can exclude it
BOOT_DRIVE=$(lsblk -ndo PKNAME "$(findmnt -n -o SOURCE /)" 2>/dev/null || true)

# Find all non-boot disk block devices
mapfile -t AVAILABLE_DRIVES < <(
    lsblk -dnpo NAME,SIZE,TYPE | awk '$3 == "disk"' | while read -r name size type; do
        dev_name=$(basename "$name")
        if [[ "$dev_name" != "$BOOT_DRIVE" ]]; then
            echo "$name"
        fi
    done
)

if [[ ${#AVAILABLE_DRIVES[@]} -eq 0 ]]; then
    echo "No additional drives detected — skipping LUKS encryption setup."
else
    echo
    echo "Detected storage drives:"
    for i in "${!AVAILABLE_DRIVES[@]}"; do
        dev="${AVAILABLE_DRIVES[$i]}"
        info=$(lsblk -dnpo NAME,SIZE,MODEL "$dev" 2>/dev/null)
        printf "  [%d] %s\n" "$((i + 1))" "$info"
    done
    echo

    read -r -p "Would you like to LUKS encrypt a storage drive? [y/N]: " ENCRYPT_CHOICE
    if [[ "${ENCRYPT_CHOICE,,}" == "y" ]]; then

        # Install cryptsetup if not present
        if ! command -v cryptsetup &>/dev/null; then
            echo "Installing cryptsetup..."
            apt-get update -qq
            apt-get install -y --no-install-recommends cryptsetup
        fi

        # --- Drive selection ---
        if [[ ${#AVAILABLE_DRIVES[@]} -eq 1 ]]; then
            SELECTED_DRIVE="${AVAILABLE_DRIVES[0]}"
            echo "Auto-selected the only available drive: $SELECTED_DRIVE"
        else
            while true; do
                read -r -p "Select drive number [1-${#AVAILABLE_DRIVES[@]}]: " DRIVE_NUM
                if [[ "$DRIVE_NUM" =~ ^[0-9]+$ ]] && (( DRIVE_NUM >= 1 && DRIVE_NUM <= ${#AVAILABLE_DRIVES[@]} )); then
                    SELECTED_DRIVE="${AVAILABLE_DRIVES[$((DRIVE_NUM - 1))]}"
                    break
                fi
                echo "Invalid selection. Try again."
            done
        fi

        # --- Destructive operation warning ---
        echo
        echo "╔══════════════════════════════════════════════════════════════╗"
        echo "║                                                            ║"
        echo "║   WARNING: ALL DATA ON $SELECTED_DRIVE WILL BE DESTROYED"
        echo "║                                                            ║"
        echo "║   This operation will:                                     ║"
        echo "║     1. Wipe ALL existing data on the selected drive        ║"
        echo "║     2. Create a new LUKS2 encrypted volume                 ║"
        echo "║     3. Format it with ext4                                 ║"
        echo "║                                                            ║"
        echo "║   This CANNOT be undone.                                   ║"
        echo "║                                                            ║"
        echo "╚══════════════════════════════════════════════════════════════╝"
        echo
        read -r -p "Type 'YES' (all caps) to confirm: " CONFIRM

        if [[ "$CONFIRM" != "YES" ]]; then
            echo "Aborted — no changes made to $SELECTED_DRIVE."
        else
            # --- Passphrase prompt (backup recovery key) ---
            echo
            echo "Enter a recovery passphrase. The Pi will auto-unlock using a"
            echo "keyfile stored on the SD card. This passphrase is a backup for"
            echo "manual recovery only."
            while true; do
                read -r -s -p "Enter LUKS passphrase: " LUKS_PASSPHRASE
                echo
                read -r -s -p "Confirm LUKS passphrase: " LUKS_PASSPHRASE_CONFIRM
                echo
                if [[ "$LUKS_PASSPHRASE" != "$LUKS_PASSPHRASE_CONFIRM" ]]; then
                    echo "Passphrases do not match. Try again."
                elif [[ ${#LUKS_PASSPHRASE} -lt 8 ]]; then
                    echo "Passphrase must be at least 8 characters."
                else
                    break
                fi
            done

            # --- Release the drive (unmount partitions, close LUKS mappings) ---
            echo "Preparing $SELECTED_DRIVE (unmounting any existing partitions)..."
            for part in $(lsblk -lnpo NAME "$SELECTED_DRIVE" | tail -n +2); do
                umount "$part" 2>/dev/null || true
            done
            # Close any existing device-mapper mappings (old LUKS, LVM, etc.)
            for dm in $(lsblk -lnpo NAME,TYPE "$SELECTED_DRIVE" | awk '$2 == "crypt" {print $1}'); do
                cryptsetup luksClose "$(basename "$dm")" 2>/dev/null || true
            done
            # Wipe partition table / filesystem signatures so cryptsetup sees a clean device
            wipefs -a "$SELECTED_DRIVE" >/dev/null 2>&1 || true

            # --- Generate random keyfile ---
            echo "Generating keyfile at /etc/terracrate/luks.key..."
            mkdir -p /etc/terracrate
            dd if=/dev/urandom of=/etc/terracrate/luks.key bs=4096 count=1 status=none
            chmod 400 /etc/terracrate/luks.key
            chown root:root /etc/terracrate/luks.key

            # --- LUKS format with passphrase ---
            echo "Formatting $SELECTED_DRIVE with LUKS2 encryption..."
            echo -n "$LUKS_PASSPHRASE" | cryptsetup luksFormat \
                --type luks2 --batch-mode "$SELECTED_DRIVE" -

            # --- Add keyfile as secondary key slot ---
            echo "Adding keyfile to LUKS volume..."
            echo -n "$LUKS_PASSPHRASE" | cryptsetup luksAddKey \
                "$SELECTED_DRIVE" /etc/terracrate/luks.key -

            # Clear passphrase from memory
            unset LUKS_PASSPHRASE LUKS_PASSPHRASE_CONFIRM

            # --- Open and verify ---
            echo "Opening LUKS volume..."
            cryptsetup luksOpen "$SELECTED_DRIVE" terracrate-store \
                --key-file /etc/terracrate/luks.key

            # --- Create ext4 filesystem ---
            echo "Creating ext4 filesystem..."
            mkfs.ext4 -L terracrate-store /dev/mapper/terracrate-store -q

            # --- Mount ---
            mkdir -p /mnt/storage
            mount /dev/mapper/terracrate-store /mnt/storage
            echo "LUKS volume mounted at /mnt/storage"

            # --- Get UUID for stable reference ---
            LUKS_UUID=$(blkid -s UUID -o value "$SELECTED_DRIVE")

            # --- Install terracrate-luks.service ---
            LUKS_SVC_SRC="$SCRIPT_DIR/config/terracrate-luks.service"
            LUKS_SVC_DST="/etc/systemd/system/terracrate-luks.service"
            if [[ -f "$LUKS_SVC_SRC" ]]; then
                sed "s|__LUKS_UUID__|$LUKS_UUID|g" "$LUKS_SVC_SRC" > "$LUKS_SVC_DST"
                echo "Installed terracrate-luks.service (UUID=$LUKS_UUID)"
            else
                echo "Error: $LUKS_SVC_SRC not found"
                exit 1
            fi

            # --- Enable terracrate-luks.service ---
            systemctl daemon-reload
            systemctl enable terracrate-luks
            echo "Enabled terracrate-luks.service"

            # --- Update docker-compose.yml to use /mnt/storage ---
            sed -i "s|^\(\s*-\s*\)./backend/api/storage:/app/storage|\1/mnt/storage:/app/storage|" \
                "$SCRIPT_DIR/docker-compose.yml"
            echo "Updated docker-compose.yml to mount /mnt/storage"

            LUKS_ENABLED=true
            echo
            echo "LUKS encryption setup complete!"
            echo "  Drive: $SELECTED_DRIVE"
            echo "  UUID:  $LUKS_UUID"
            echo "  Keyfile: /etc/terracrate/luks.key"
            echo "  Mount point: /mnt/storage"
        fi
    fi
fi
fi # end LUKS_ENABLED==false fresh-setup block

# ---------------------------------------------------------------------------
# 6. Install and enable the TerraCrate docker compose service
# ---------------------------------------------------------------------------
RUN_USER="${SUDO_USER:-pi}"
TERRACRATE_SVC_SRC="$SCRIPT_DIR/config/terracrate.service"
TERRACRATE_SVC_DST="/etc/systemd/system/terracrate.service"
if [[ -f "$TERRACRATE_SVC_SRC" ]]; then
    # Template User= and WorkingDirectory= from the actual install location
    sed -e "s|^User=.*|User=$RUN_USER|" \
        -e "s|^WorkingDirectory=.*|WorkingDirectory=$SCRIPT_DIR|" \
        "$TERRACRATE_SVC_SRC" > "$TERRACRATE_SVC_DST"

    # If LUKS is enabled, patch the unit to depend on terracrate-luks.service
    if [[ "$LUKS_ENABLED" == "true" ]]; then
        sed -i -e 's|^After=.*|After=terracrate-luks.service network.target docker.service|' \
               -e '/^After=/a Requires=terracrate-luks.service\nWants=docker.service' \
               "$TERRACRATE_SVC_DST"
        echo "Patched terracrate.service with LUKS dependency"
    fi

    systemctl daemon-reload
    if [[ "$LUKS_ENABLED" == "true" ]]; then
        systemctl reset-failed terracrate-luks 2>/dev/null || true
        systemctl start terracrate-luks
    fi
    systemctl reset-failed terracrate 2>/dev/null || true
    systemctl enable terracrate
    systemctl start terracrate
    echo "Installed, enabled, and started terracrate.service -> $TERRACRATE_SVC_DST"
else
    echo "Warning: $TERRACRATE_SVC_SRC not found — skipping terracrate.service install"
fi

# Install and enable the systemd service
WIFI_SVC_SRC="$SCRIPT_DIR/config/wifi-fallback.service"
WIFI_SVC_DST="/etc/systemd/system/wifi-fallback.service"
if [[ -f "$WIFI_SVC_SRC" ]]; then
    cp "$WIFI_SVC_SRC" "$WIFI_SVC_DST"
    systemctl daemon-reload
    systemctl enable wifi-fallback
    echo "Installed and enabled wifi-fallback.service -> $WIFI_SVC_DST"
else
    echo "Warning: $WIFI_SVC_SRC not found — skipping wifi-fallback.service install"
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo
echo "✅ Host setup complete!"
echo "   Device will be discoverable at: https://${MDNS_HOSTNAME}.local"
echo "   (Customize MDNS_HOSTNAME in .env to change the hostname)"
echo
echo "WiFi fallback: if the Pi cannot join a known network on boot it will"
echo "  broadcast an AP — SSID is TerraCrate-AP, passphrase is in $ENV_FILE (AP_PASSPHRASE)"
if [[ "$LUKS_ENABLED" == "true" ]]; then
    echo
    echo "LUKS encryption: storage drive is encrypted and auto-unlocks on boot."
    echo "  Keyfile: /etc/terracrate/luks.key (on SD card)"
    echo "  Recovery: use your passphrase with cryptsetup luksOpen if the keyfile is lost"
    echo "  Units: terracrate-luks.service -> terracrate.service (patched with LUKS dependency)"
fi

