/**
 * API Service Layer for TerraCrate Frontend
 *
 * All response shapes derive from the protobuf-generated JSON types in
 * src/gen (the wire contract's single source of truth, generated by buf from
 * proto/terracrate/v1). The `Narrowed` helper refines those wire types with
 * app-level knowledge (literal unions, fields the backend always emits);
 * if the wire contract drifts — a field renamed, removed, or retyped — these
 * definitions stop compiling.
 *
 * proto3 JSON notes: int64 fields (file sizes) arrive as strings and are
 * coerced to numbers here; unset optional fields are omitted; unset message
 * fields (timestamps) are null.
 */

import { config } from '../config';

import type {
  UserDetailJson,
  RevokedCertificateJson,
  CertStatusResponseJson,
} from '../gen/terracrate/v1/user_pb';
import type {
  FolderPermissionJson,
  EffectivePermissionEntryJson,
} from '../gen/terracrate/v1/permission_pb';
import type {
  SystemSettingsJson,
  DashboardStatsJson,
} from '../gen/terracrate/v1/settings_pb';
import type {
  DomainConfigJson,
  DomainPermissionJson,
} from '../gen/terracrate/v1/domain_pb';
import type {
  GroupPermissionJson,
  GroupSummaryJson,
  GroupDetailJson,
} from '../gen/terracrate/v1/group_pb';
import type {
  AuditLogEntryJson,
  AuditLogStatsJson,
  ListAuditLogsResponseJson,
} from '../gen/terracrate/v1/audit_pb';
import type {
  GetSystemLogsResponseJson,
  SystemLogLineJson,
} from '../gen/terracrate/v1/system_pb';
import type { FileItemJson, ListFilesResponseJson } from '../gen/terracrate/v1/file_pb';
import type { ClaimCertResponseJson } from '../gen/terracrate/v1/claim_pb';

// =============================================================================
// Wire-derived types
// =============================================================================

/**
 * Refine a generated wire type: override keys must exist on the wire type,
 * so renames/removals in the protos become compile errors here.
 */
type Narrowed<Wire, Overrides extends { [K in keyof Wire]?: unknown }> = Omit<
  Wire,
  keyof Overrides
> &
  Overrides;

export type User = Narrowed<
  UserDetailJson,
  {
    id: number;
    email: string;
    role: 'admin' | 'user';
    requiresPasswordChange: boolean;
    isApproved: boolean;
    createdAt: string | null;
    lastLogin: string | null;
    groups: { id: number; name: string }[];
    certRevoked: boolean;
    certIssuedAt: string | null;
    certExpiresAt: string | null;
    folderPermissions?: FolderPermission[];
  }
>;

export type SystemSettings = Narrowed<
  SystemSettingsJson,
  {
    id: number;
    authMethod: 'email' | 'email+password' | 'username+password';
    tlsEnabled: boolean;
    httpsPort: number;
    deviceName: string;
    updatedAt: string | null;
    smtpEnabled: boolean;
    smtpHost: string;
    smtpPort: number;
    smtpUsername: string;
    smtpPassword: string;
    smtpFromEmail: string;
    smtpUseTls: boolean;
    allowedDomains: string[];
  }
>;

/**
 * Tri-state grant: 'allow' / 'deny' override lower tiers; an absent or null
 * value defers to them (the API omits unset flags).
 */
export type PermissionState = 'allow' | 'deny' | null;

export type FolderPermission = Narrowed<
  FolderPermissionJson,
  {
    id: number;
    userId: number;
    path: string;
    read?: PermissionState;
    write?: PermissionState;
    createdAt: string | null;
  }
>;

export type FileItem = Narrowed<
  FileItemJson,
  {
    id?: string;
    name: string;
    type: 'file' | 'folder';
    path: string;
    size?: number; // coerced from the int64 wire string
    modifiedAt: string;
    parentPath?: string;
  }
>;

export type DashboardStats = Narrowed<
  DashboardStatsJson,
  {
    userCount: number;
    fileCount: number;
    folderCount: number;
    totalSize: number; // coerced from the int64 wire string
    tlsEnabled: boolean;
  }
>;

export interface ApiError {
  error: string;
  code: string;
}

export interface LoginCredentials {
  email: string;
  password: string;
}

export interface SignupCredentials {
  email: string;
  password: string;
  username?: string;
}

// --- Domain Config ---

export type DomainPermission = Narrowed<
  DomainPermissionJson,
  {
    id: number;
    domainId: number;
    path: string;
    read: boolean;
    write: boolean;
    createdAt: string | null;
  }
>;

export type DomainConfig = Narrowed<
  DomainConfigJson,
  {
    id: number;
    domain: string;
    permissions: DomainPermission[];
    createdAt: string | null;
    updatedAt: string | null;
  }
>;

// --- Groups ---

export type GroupPermission = Narrowed<
  GroupPermissionJson,
  {
    id: number;
    groupId: number;
    path: string;
    read: boolean;
    write: boolean;
    createdAt: string | null;
  }
>;

export type GroupSummary = Narrowed<
  GroupSummaryJson,
  {
    id: number;
    name: string;
    description?: string | null;
    memberCount: number;
    permissionCount: number;
    createdAt: string | null;
    updatedAt: string | null;
  }
>;

export type GroupDetail = Narrowed<
  GroupDetailJson,
  {
    id: number;
    name: string;
    description?: string | null;
    memberCount: number;
    permissionCount: number;
    createdAt: string | null;
    updatedAt: string | null;
    members: { id: number; email: string }[];
    permissions: GroupPermission[];
  }
>;

// --- Effective Permissions ---

export type EffectivePermissionEntry = Narrowed<
  EffectivePermissionEntryJson,
  {
    domain: { canRead?: boolean; canWrite?: boolean } | null;
    groups: { groupId?: number; groupName?: string; canRead?: boolean; canWrite?: boolean }[];
    groupMerged: { canRead?: boolean; canWrite?: boolean } | null;
    user: { canRead?: string; canWrite?: string } | null;
    effective: { canRead: boolean; canWrite: boolean; source: string };
  }
>;

export type EffectivePermissions = Record<string, EffectivePermissionEntry>;

// --- Certificates ---

export type RevokedCertificate = Narrowed<
  RevokedCertificateJson,
  {
    id: number;
    serialNumber: string;
    revokedAt: string | null;
    reason: string;
  }
>;

export type CertStatus = Narrowed<
  CertStatusResponseJson,
  {
    issuedAt: string | null;
    expiresAt: string | null;
    isRevoked: boolean;
    revocationHistory: RevokedCertificate[];
  }
>;

/** One-time claim redemption: the .p12 arrives base64-encoded. */
export type ClaimCertResult = Narrowed<
  ClaimCertResponseJson,
  {
    p12: string;
    filename: string;
    password: string;
    passwordIsLogin: boolean;
    email: string;
  }
>;

// --- Audit Logs ---

export type AuditLogEntry = Narrowed<
  AuditLogEntryJson,
  {
    id: number;
    timestamp: string | null;
    action: string;
    status: 'success' | 'failure';
  }
>;

export type AuditLogResponse = Narrowed<
  ListAuditLogsResponseJson,
  {
    logs: AuditLogEntry[];
    total: number;
    page: number;
    limit: number;
  }
>;

export type AuditLogStats = Narrowed<
  AuditLogStatsJson,
  {
    total: number;
    today: number;
    failedAuthToday: number;
    activeUsersToday: number;
  }
>;

export interface AuditLogFilters {
  page?: number;
  limit?: number;
  action?: string;
  category?: string;
  userEmail?: string;
  status?: string;
  since?: string;
  search?: string;
}

export type SystemLogEntry = Narrowed<SystemLogLineJson, { timestamp: string; line: string }>;

export type SystemLogResponse = Narrowed<
  GetSystemLogsResponseJson,
  {
    logs: SystemLogEntry[];
    container: string;
    available: boolean;
    error?: string | null;
  }
>;

export type AuditTab = 'all' | 'files' | 'security' | 'system';

// =============================================================================
// Wire helpers
// =============================================================================

function toFileItem(f: FileItemJson): FileItem {
  return {
    id: f.id,
    name: f.name ?? '',
    path: f.path ?? '',
    type: f.type === 'folder' ? 'folder' : 'file',
    size: Number(f.size ?? 0),
    modifiedAt: f.modifiedAt ?? '',
    parentPath: f.parentPath,
  };
}

function toFileListing(res: ListFilesResponseJson): {
  files: FileItem[];
  currentPath: string;
  parentPath: string | null;
} {
  return {
    files: (res.files ?? []).map(toFileItem),
    currentPath: res.currentPath ?? '/',
    parentPath: res.parentPath ?? null,
  };
}

// =============================================================================
// API Client Class
// =============================================================================

class ApiClient {
  private baseUrl: string;
  private token: string | null = null;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
    // Load token from localStorage on init
    this.token = localStorage.getItem('auth_token');
  }

  /**
   * Set authentication token
   */
  setToken(token: string | null) {
    this.token = token;
    if (token) {
      localStorage.setItem('auth_token', token);
    } else {
      localStorage.removeItem('auth_token');
    }
  }

  /**
   * Get current token
   */
  getToken(): string | null {
    return this.token;
  }

  /**
   * Make HTTP request with error handling
   */
  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const url = `${this.baseUrl}${endpoint}`;

    // Normalize headers to a plain object
    let normalizedHeaders: Record<string, string> = { 'Content-Type': 'application/json' };
    if (options.headers) {
      if (options.headers instanceof Headers) {
        options.headers.forEach((value, key) => {
          normalizedHeaders[key] = value;
        });
      } else if (Array.isArray(options.headers)) {
        options.headers.forEach(([key, value]) => {
          normalizedHeaders[key] = value;
        });
      } else {
        normalizedHeaders = { ...normalizedHeaders, ...(options.headers as Record<string, string>) };
      }
    }

    // Add Authorization header if token exists
    // Reload token from localStorage in case it was set after initialization
    if (!this.token) {
      this.token = localStorage.getItem('auth_token');
    }

    if (this.token) {
      normalizedHeaders['Authorization'] = `Bearer ${this.token}`;
    }

    try {
      const response = await fetch(url, {
        ...options,
        headers: normalizedHeaders,
      });

      // Handle non-JSON responses (like file downloads)
      const contentType = response.headers.get('content-type');
      if (contentType && !contentType.includes('application/json')) {
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        return response as T;
      }

      // Parse JSON response
      const data = await response.json();

      if (!response.ok) {
        const apiError: ApiError = data;
        throw new Error(apiError.error || `HTTP ${response.status}: ${response.statusText}`);
      }

      return data as T;
    } catch (error) {
      // Network or parsing errors
      if (error instanceof Error) {
        throw error;
      }
      throw new Error('Network request failed');
    }
  }

  // ===========================================================================
  // Authentication Endpoints
  // ===========================================================================

  async login(credentials: LoginCredentials): Promise<{ token: string; user: User }> {
    const response = await this.request<{ token: string; user: User }>(
      '/api/v1/auth/login',
      {
        method: 'POST',
        body: JSON.stringify(credentials),
      }
    );

    // Automatically set token
    this.setToken(response.token);

    return response;
  }

  async signup(
    credentials: SignupCredentials
  ): Promise<{ token: string; user: User; claimUrl?: string }> {
    const response = await this.request<{ token: string; user: User; claimUrl?: string }>(
      '/api/v1/auth/signup',
      {
        method: 'POST',
        body: JSON.stringify(credentials),
      }
    );

    // Automatically set token
    this.setToken(response.token);

    return response;
  }

  async logout(): Promise<{ success: boolean }> {
    const response = await this.request<{ success: boolean }>(
      '/api/v1/auth/logout',
      {
        method: 'POST',
      }
    );

    // Clear token
    this.setToken(null);

    return response;
  }

  async getCurrentUser(): Promise<{ user: User }> {
    return this.request<{ user: User }>('/api/v1/auth/me');
  }

  async refreshToken(): Promise<{ token: string }> {
    const response = await this.request<{ token: string }>(
      '/api/v1/auth/refresh',
      {
        method: 'POST',
      }
    );

    // Update token
    this.setToken(response.token);

    return response;
  }

  async changePassword(currentPassword: string, newPassword: string): Promise<{ token: string; user: User }> {
    const response = await this.request<{ token: string; user: User }>(
      '/api/v1/auth/change-password',
      {
        method: 'POST',
        body: JSON.stringify({ currentPassword, newPassword }),
      }
    );

    // Update token
    this.setToken(response.token);

    return response;
  }

  // ===========================================================================
  // Certificate Claim (public, one-time link)
  // ===========================================================================

  async claimCert(token: string): Promise<ClaimCertResult> {
    return this.request<ClaimCertResult>('/api/v1/certs/claim', {
      method: 'POST',
      body: JSON.stringify({ token }),
    });
  }

  // ===========================================================================
  // System Settings Endpoints
  // ===========================================================================

  async getSettings(): Promise<SystemSettings> {
    return this.request<SystemSettings>('/api/v1/settings');
  }

  async updateSettings(settings: Partial<SystemSettings>): Promise<SystemSettings> {
    return this.request<SystemSettings>('/api/v1/settings', {
      method: 'PUT',
      body: JSON.stringify(settings),
    });
  }

  // ===========================================================================
  // User Management Endpoints
  // ===========================================================================

  async listUsers(params?: {
    search?: string;
    page?: number;
    limit?: number;
  }): Promise<{
    users: User[];
    total: number;
    page: number;
    limit: number;
  }> {
    const queryParams = new URLSearchParams();
    if (params?.search) queryParams.append('search', params.search);
    if (params?.page) queryParams.append('page', params.page.toString());
    if (params?.limit) queryParams.append('limit', params.limit.toString());

    const queryString = queryParams.toString();
    const endpoint = `/api/v1/users${queryString ? `?${queryString}` : ''}`;

    return this.request(endpoint);
  }

  async createUser(userData: {
    email: string;
    password?: string;
    role?: 'admin' | 'user';
  }): Promise<{ user: User; claimUrl: string }> {
    return this.request<{ user: User; claimUrl: string }>('/api/v1/users', {
      method: 'POST',
      body: JSON.stringify(userData),
    });
  }

  async getUser(userId: number): Promise<{ user: User }> {
    return this.request<{ user: User }>(`/api/v1/users/${userId}`);
  }

  async updateUser(
    userId: number,
    userData: Partial<{ email: string; password: string; role: 'admin' | 'user'; approved: boolean }>
  ): Promise<{ user: User }> {
    return this.request<{ user: User }>(`/api/v1/users/${userId}`, {
      method: 'PUT',
      body: JSON.stringify(userData),
    });
  }

  async deleteUser(userId: number): Promise<{ success: boolean }> {
    return this.request<{ success: boolean }>(`/api/v1/users/${userId}`, {
      method: 'DELETE',
    });
  }

  // ===========================================================================
  // Certificate Revocation & Re-issue Endpoints
  // ===========================================================================

  async revokeCert(userId: number): Promise<{ message: string; revokedSerial?: string; user: User }> {
    return this.request(`/api/v1/users/${userId}/revoke-cert`, {
      method: 'POST',
    });
  }

  async reissueCert(userId: number): Promise<{ message: string; user: User; claimUrl: string }> {
    return this.request(`/api/v1/users/${userId}/reissue-cert`, {
      method: 'POST',
    });
  }

  async getCertStatus(userId: number): Promise<CertStatus> {
    return this.request(`/api/v1/users/${userId}/cert-status`);
  }

  // ===========================================================================
  // Folder Permissions Endpoints
  // ===========================================================================

  async getUserPermissions(userId: number): Promise<{ permissions: FolderPermission[] }> {
    return this.request<{ permissions: FolderPermission[] }>(
      `/api/v1/users/${userId}/permissions`
    );
  }

  async updateUserPermissions(
    userId: number,
    permissions: Array<{ path: string; read: PermissionState; write: PermissionState }>
  ): Promise<{ permissions: FolderPermission[] }> {
    return this.request<{ permissions: FolderPermission[] }>(
      `/api/v1/users/${userId}/permissions`,
      {
        method: 'PUT',
        body: JSON.stringify({ permissions }),
      }
    );
  }

  async listFolders(): Promise<{ folders: Array<{ path: string; name: string }> }> {
    return this.request<{ folders: Array<{ path: string; name: string }> }>(
      '/api/v1/folders'
    );
  }

  // ===========================================================================
  // Guest File Endpoints (no auth required)
  // ===========================================================================

  async listGuestFiles(params?: {
    path?: string;
    search?: string;
  }): Promise<{
    files: FileItem[];
    currentPath: string;
    parentPath: string | null;
  }> {
    const queryParams = new URLSearchParams();
    if (params?.path) queryParams.append('path', params.path);
    if (params?.search) queryParams.append('search', params.search);

    const queryString = queryParams.toString();
    const endpoint = `/api/v1/guest/files${queryString ? `?${queryString}` : ''}`;

    return toFileListing(await this.request<ListFilesResponseJson>(endpoint));
  }

  getGuestDownloadUrl(path: string): string {
    const queryParams = new URLSearchParams({ path });
    return `${this.baseUrl}/api/v1/guest/files/download?${queryParams.toString()}`;
  }

  // ===========================================================================
  // File Operations Endpoints
  // ===========================================================================

  async listFiles(params?: {
    path?: string;
    search?: string;
  }): Promise<{
    files: FileItem[];
    currentPath: string;
    parentPath: string | null;
  }> {
    const queryParams = new URLSearchParams();
    if (params?.path) queryParams.append('path', params.path);
    if (params?.search) queryParams.append('search', params.search);

    const queryString = queryParams.toString();
    const endpoint = `/api/v1/files${queryString ? `?${queryString}` : ''}`;

    return toFileListing(await this.request<ListFilesResponseJson>(endpoint));
  }

  async uploadFile(file: File, path: string = ''): Promise<{ file: FileItem }> {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('path', path);

    const url = `${this.baseUrl}/api/v1/files/upload`;
    const headers: HeadersInit = {};

    if (this.token) {
      headers['Authorization'] = `Bearer ${this.token}`;
    }

    const response = await fetch(url, {
      method: 'POST',
      headers,
      body: formData,
    });

    if (!response.ok) {
      const contentType = response.headers.get('content-type');
      if (contentType && contentType.includes('application/json')) {
        const error = await response.json();
        throw new Error(error.error || 'Upload failed');
      }
      throw new Error(`Upload failed (HTTP ${response.status})`);
    }

    const data: { file: FileItemJson } = await response.json();
    return { file: toFileItem(data.file) };
  }

  async downloadFile(path: string): Promise<Response> {
    const queryParams = new URLSearchParams({ path });
    const endpoint = `/api/v1/files/download?${queryParams.toString()}`;

    return this.request<Response>(endpoint);
  }

  async previewFile(path: string): Promise<Response> {
    const url = `${this.baseUrl}/api/v1/files/preview?path=${encodeURIComponent(path)}`;
    const headers: Record<string, string> = {};
    if (this.token) headers['Authorization'] = `Bearer ${this.token}`;
    const response = await fetch(url, { headers });
    if (!response.ok) throw new Error(`Preview failed (HTTP ${response.status})`);
    return response;
  }

  async previewGuestFile(path: string): Promise<Response> {
    const url = `${this.baseUrl}/api/v1/guest/files/download?path=${encodeURIComponent(path)}`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Preview failed (HTTP ${response.status})`);
    return response;
  }

  async createDirectory(path: string, name: string): Promise<{ folder: { name: string; path: string } }> {
    return this.request<{ folder: { name: string; path: string } }>(
      '/api/v1/files/mkdir',
      {
        method: 'POST',
        body: JSON.stringify({ path, name }),
      }
    );
  }

  async deleteFile(path: string): Promise<{ success: boolean }> {
    const queryParams = new URLSearchParams({ path });
    const endpoint = `/api/v1/files?${queryParams.toString()}`;

    return this.request<{ success: boolean }>(endpoint, {
      method: 'DELETE',
    });
  }

  async renameFile(path: string, newName: string): Promise<{ success: boolean; newPath: string; newName: string }> {
    return this.request<{ success: boolean; newPath: string; newName: string }>(
      '/api/v1/files/rename',
      {
        method: 'POST',
        body: JSON.stringify({ path, newName }),
      }
    );
  }

  async moveFile(srcPath: string, destDir: string): Promise<{ success: boolean; newPath: string }> {
    return this.request<{ success: boolean; newPath: string }>(
      '/api/v1/files/move',
      {
        method: 'POST',
        body: JSON.stringify({ srcPath, destDir }),
      }
    );
  }

  // ===========================================================================
  // Domain Config Endpoints
  // ===========================================================================

  async listDomains(): Promise<{ domains: DomainConfig[] }> {
    return this.request<{ domains: DomainConfig[] }>('/api/v1/domains');
  }

  async createDomain(data: {
    domain: string;
    permissions?: Array<{ path: string; read: boolean; write: boolean }>;
  }): Promise<{ domain: DomainConfig }> {
    return this.request<{ domain: DomainConfig }>('/api/v1/domains', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async getDomain(domainId: number): Promise<{ domain: DomainConfig }> {
    return this.request<{ domain: DomainConfig }>(`/api/v1/domains/${domainId}`);
  }

  async updateDomain(
    domainId: number,
    data: {
      domain?: string;
      permissions?: Array<{ path: string; read: boolean; write: boolean }>;
    }
  ): Promise<{ domain: DomainConfig }> {
    return this.request<{ domain: DomainConfig }>(`/api/v1/domains/${domainId}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
  }

  async deleteDomain(domainId: number): Promise<{ success: boolean }> {
    return this.request<{ success: boolean }>(`/api/v1/domains/${domainId}`, {
      method: 'DELETE',
    });
  }

  // ===========================================================================
  // Group Endpoints
  // ===========================================================================

  async listGroups(): Promise<{ groups: GroupSummary[] }> {
    return this.request<{ groups: GroupSummary[] }>('/api/v1/groups');
  }

  async createGroup(data: { name: string; description?: string }): Promise<{ group: GroupSummary }> {
    return this.request<{ group: GroupSummary }>('/api/v1/groups', {
      method: 'POST',
      body: JSON.stringify(data),
    });
  }

  async getGroup(groupId: number): Promise<{ group: GroupDetail }> {
    return this.request<{ group: GroupDetail }>(`/api/v1/groups/${groupId}`);
  }

  async updateGroup(
    groupId: number,
    data: { name?: string; description?: string }
  ): Promise<{ group: GroupDetail }> {
    return this.request<{ group: GroupDetail }>(`/api/v1/groups/${groupId}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });
  }

  async deleteGroup(groupId: number): Promise<{ success: boolean }> {
    return this.request<{ success: boolean }>(`/api/v1/groups/${groupId}`, {
      method: 'DELETE',
    });
  }

  async updateGroupPermissions(
    groupId: number,
    permissions: Array<{ path: string; read: boolean; write: boolean }>
  ): Promise<{ permissions: GroupPermission[] }> {
    return this.request<{ permissions: GroupPermission[] }>(
      `/api/v1/groups/${groupId}/permissions`,
      {
        method: 'PUT',
        body: JSON.stringify({ permissions }),
      }
    );
  }

  async updateGroupMembers(
    groupId: number,
    userIds: number[]
  ): Promise<{ group: GroupDetail }> {
    return this.request<{ group: GroupDetail }>(
      `/api/v1/groups/${groupId}/members`,
      {
        method: 'PUT',
        body: JSON.stringify({ userIds }),
      }
    );
  }

  // ===========================================================================
  // Enhanced User Permission Endpoints
  // ===========================================================================

  async getEffectivePermissions(userId: number): Promise<{ permissions: EffectivePermissions }> {
    return this.request<{ permissions: EffectivePermissions }>(
      `/api/v1/users/${userId}/effective-permissions`
    );
  }

  async updateUserGroups(userId: number, groupIds: number[]): Promise<{ user: User }> {
    return this.request<{ user: User }>(
      `/api/v1/users/${userId}/groups`,
      {
        method: 'PUT',
        body: JSON.stringify({ groupIds }),
      }
    );
  }

  // ===========================================================================
  // Dashboard Stats Endpoint
  // ===========================================================================

  async getDashboardStats(): Promise<DashboardStats> {
    const stats = await this.request<DashboardStatsJson>('/api/v1/stats/dashboard');
    return {
      userCount: stats.userCount ?? 0,
      fileCount: stats.fileCount ?? 0,
      folderCount: stats.folderCount ?? 0,
      totalSize: Number(stats.totalSize ?? 0),
      tlsEnabled: stats.tlsEnabled ?? true,
    };
  }

  // ===========================================================================
  // Audit Log Endpoints
  // ===========================================================================

  async getAuditLogs(filters: AuditLogFilters = {}): Promise<AuditLogResponse> {
    const params = new URLSearchParams();
    if (filters.page) params.set('page', String(filters.page));
    if (filters.limit) params.set('limit', String(filters.limit));
    if (filters.action) params.set('action', filters.action);
    if (filters.category) params.set('category', filters.category);
    if (filters.userEmail) params.set('user_email', filters.userEmail);
    if (filters.status) params.set('status', filters.status);
    if (filters.since) params.set('since', filters.since);
    if (filters.search) params.set('search', filters.search);
    const qs = params.toString();
    return this.request<AuditLogResponse>(`/api/v1/audit-logs${qs ? `?${qs}` : ''}`);
  }

  async getAuditLogStats(): Promise<AuditLogStats> {
    return this.request<AuditLogStats>('/api/v1/audit-logs/stats');
  }

  async getSystemLogs(container = 'backend', tail = 200): Promise<SystemLogResponse> {
    return this.request<SystemLogResponse>(
      `/api/v1/system/logs?container=${encodeURIComponent(container)}&tail=${tail}`
    );
  }
}

// =============================================================================
// Export singleton instance
// =============================================================================

export const api = new ApiClient(config.apiBaseUrl);
export default api;
