stateDiagram-v2
    [*] --> Dormant

    Dormant --> Advertising: Button pressed

    Advertising --> Active: 

    Active --> Advertising: 
    Active --> Shutdown: 

    Advertising --> Shutdown: 
    Dormant --> Shutdown: 

    Shutdown --> [*] 