name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans weekly on Monday at 8 AM UTC
    - cron: '0 8 * * 1'

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  python-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install bandit safety
        if [ -f backend/scripts/dependencies.txt ]; then 
          pip install -r backend/scripts/dependencies.txt
        fi
    
    - name: Run Bandit security linter
      run: |
        bandit -r backend/ distribution/src/ -f json -o bandit-report.json || true
        bandit -r backend/ distribution/src/ || true
      continue-on-error: true
    
    - name: Check for known vulnerabilities with Safety
      run: |
        safety check --json || true
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
        retention-days: 30

  docker-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      working-directory: ./backend/api
      run: |
        docker build -f server/Dockerfile -t thumbsup-server:scan .
        docker build -f client/Dockerfile -t thumbsup-client:scan .
    
    - name: Scan server image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'thumbsup-server:scan'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'
    
    - name: Scan client image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'thumbsup-client:scan'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'

  secret-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Scan for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
