name: Security Scanning

permissions:
  contents: read
  security-events: write  # Required for uploading SARIF results

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans weekly on Monday at 8 AM UTC
    - cron: '0 8 * * 1'

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  python-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install bandit safety
        if [ -f backend/scripts/dependencies.txt ]; then 
          pip install -r backend/scripts/dependencies.txt
        fi
    
    - name: Run Bandit security linter
      run: |
        bandit -r backend/ distribution/src/ -f json -o bandit-report.json || true
        bandit -r backend/ distribution/src/ || true
      continue-on-error: true
    
    - name: Check for known vulnerabilities with Safety
      run: |
        safety check --json || true
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
        retention-days: 30

  docker-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Generate PKI certificates for Docker build
      run: |
        cd backend/pki
        pip install cryptography
        python gen_selfsigned.py \
          --server-cn localhost \
          --client-cn scan-client \
          --validity-days 365 \
          --output-dir .
    
    - name: Build Docker images
      working-directory: ./backend
      run: |
        docker build -f api/server/Dockerfile -t thumbsup-server:scan .
        docker build -f api/client/Dockerfile -t thumbsup-client:scan .
    
    - name: Scan server image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'thumbsup-server:scan'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'
    
    - name: Scan client image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'thumbsup-client:scan'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'

  secret-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Scan for secrets (git diff mode)
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --only-verified
      continue-on-error: true
    
    - name: Scan for secrets (full filesystem scan)
      if: github.event_name == 'schedule'
      run: |
        docker run --rm -v "$(pwd):/scan" trufflesecurity/trufflehog:latest filesystem /scan --only-verified --json > trufflehog-results.json || true
        if [ -s trufflehog-results.json ]; then
          echo "⚠️ Potential secrets found!"
          cat trufflehog-results.json
        else
          echo "✓ No secrets detected"
        fi
